import type { Metadata, Viewport } from "next";
import Head from 'next/head';
import Image from "next/image";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/effect-fade";
import "@/css/fontello/css/fontello.css";
import "lenis/dist/lenis.css";
import { Header, TopBar } from "@/components";
import { routing } from "@/i18n/routing";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import Link from "next/link";
import { ChatPrimary, Whatsapp } from "@/assets";
import AppFooter from "@/components/layout/footer";
import { Suspense } from "react";
import SuspenseLoader from "@/components/ui/suspense";
import { NextIntlClientProvider } from "next-intl";
import ScrollContext from "@/components/wrapper/scrollcontext";
import Script from "next/script";
import { API_CLIENT } from "@/services";
import { notFound } from "next/navigation";

const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: "#0078bd",
};

export const metadata: Metadata = {
  title: "Asian Health Tourism",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  const langs = await API_CLIENT.fetchMasterLangs();
  const contact = await API_CLIENT.fetchContact();

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }


  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <Head>
      <meta name="googlebot" content="noindex,nofollow" />
      </Head>
      <NextIntlClientProvider messages={messages}>
        <body className={opensans.className}>
          <Suspense fallback={<SuspenseLoader />}>
            <ScrollContext>
              <TopBar langs={langs} contact={contact} locale={locale} />
              <Header langs={langs} />
              {children}
              <div className="aside-chat-option">
                <ul className="appearance-none flex flex-col gap-4">
                  <li>
                    <Link href="/" className="rotate-hover">
                      <Image src={Whatsapp} alt="ChatNow" />
                    </Link>
                  </li>
                  <li>
                    <Link href="/" className="rotate-hover">
                      <Image src={ChatPrimary} alt="ChatNow" />
                    </Link>
                  </li>
                </ul>
              </div>
              <AppFooter />
            </ScrollContext>
          </Suspense>
          <Script
            src="https://unpkg.com/lenis@1.1.14/dist/lenis.min.js"
            strategy="beforeInteractive"
          ></Script>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
function setRequestLocale(locale: string) {
  throw new Error("Function not implemented.");
}

